//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrackerWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public int ProjectId { get; set; }
        public int StatusTaskId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual StatusTask StatusTask { get; set; }
    }
}
